#!/bin/sh

# resolves dependencies of source files
# (C) 2007-2008 magicant
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


tmp=".deptmp"
trap 'rm -rf "${tmp}"' EXIT HUP INT QUIT ABRT ALRM TERM PIPE USR1 USR2
umask u=rwx,go=rx
mkdir "${tmp}"

csearch () {
    if ! [ -r "$1" ]
    then
	return
    fi
    if [ -r "${tmp}/$1" ]
    then
	cat "${tmp}/$1"
    else
	rm -rf "${tmp}/$1"
	sed -e '
	    /^[[:blank:]]*#[[:blank:]]*include[[:blank:]]*"[^"]*"$/ {
	      s/^[[:blank:]]*#[[:blank:]]*include[[:blank:]]*"\([^"]*\)"/\1/
	      p
	    }
	    d
	    ' "$1" | \
	while read -r dep
	do
	    echo "${dep}"
	    csearch "${dep}"
	done | \
	tee "${tmp}/$1"
    fi
}

for source
do
    case "${source}" in
	*.c)
	csearch "${source}" | sort -u | xargs echo "${source%.c}.o:"
	;;
    esac
done


# vim: set ts=8 sts=4 sw=4 noet:
