name: C CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Kesin11/actions-timeline@v2
    - uses: actions/checkout@v4
    - name: preparation
      run: |
        sudo apt-get update
        sudo apt-get install asciidoc gettext libncurses-dev
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make -j$(nproc) distcheck
    - name: make check as root
      run: sudo make -j$(nproc) check
